- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: test sleep async
    shell: ping www.baidu.com -c 10 > /tmp/testfile
    async: 20
    poll: 0
    register: sleep_test


  - name: test get log async
    async_log:
      jid: "{{ sleep_test.ansible_job_id }}"
      tail_file: "/tmp/testfile"
    register: job_result
    retries: 999999
    delay: 1
    until: job_result.finished
